issuer: http://localhost:5556/dex
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556

staticClients:
- id: oauth3-dev
  redirectURIs:
  - 'http://localhost:8080/auth/callback/dex'
  - 'http://app:8080/auth/callback/dex'
  name: 'OAuth3 Dev'
  secret: dex-secret
  # Skip the approval page for easier automated testing
  skipApproval: true

enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash for "password"
  hash: "$2b$10$0PrvgqBsWaqJPOmV8HhKSOR1kr.T7xG7OdEc7Nb0u56kPSydXk3ii"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

oauth2:
  skipApprovalScreen: true
  responseTypes: ["code", "token", "id_token"]
